### ISSUE TITLE
Play 2.5.x compatibility

### ISSUE THREAD

**Issue by gmalouf** [Kanaka-io/play-monadic-actions#24]
Has anyone tried using this with Play 2.5.x?  We are hoping to upgrade soon but have monadic-actions as a dependency...

**Comment by vil1** [comment]
Hi Gary, 

To be honest, I've not worked with new/up-to-date play projects lately, so I've never personally checked that the lib works correctly with Play 2.5 (but I'm not aware of changes in Play that would make it incompatible either).
We're in the process of writing a 2.0 version right now, and since it took a bit longer than expected (but should not take much longer), I'll consider make it depend on play 2.5 by default.

Cheers

**Comment by vil1** [comment]
Solved in 2.0.0-RC1
